services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./wok:/wok
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
  
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password

    volumes:
      - ./data/postgres:/var/lib/postgresql/data