# Generated by Django 4.1.5 on 2023-02-04 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_group', models.CharField(max_length=255, verbose_name='Группа еды')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Группа еды',
                'verbose_name_plural': 'Группа еды',
            },
        ),
        migrations.CreateModel(
            name='Ing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=100, verbose_name='Ингридиенты')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'База ингридиентов',
                'verbose_name_plural': 'База ингридиентов',
                'ordering': ['ing_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=255, verbose_name='Тип еды')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип еды',
                'verbose_name_plural': 'Тип еды',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 100 символов', max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Картинка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('moderated', models.BooleanField(default=False, verbose_name='Проверено модерацией')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrecipe.group', verbose_name='Group of food')),
                ('ingredients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrecipe.ing', verbose_name='Ингридиенты')),
                ('likes', models.ManyToManyField(blank=True, related_name='postcomments', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_ok', to='foodrecipe.post')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrecipe.type', verbose_name='Food type')),
            ],
            options={
                'verbose_name': 'Создать пост',
                'verbose_name_plural': 'Создать посты',
            },
        ),
    ]
