# Generated by Django 4.2.3 on 2023-10-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='object_id',
        ),
    ]
