# Generated by Django 4.2.3 on 2023-10-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '__first__'),
        ('follow_likes', '0003_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_post', to='userprofile.profile'),
        ),
    ]
