# Generated by Django 4.2.3 on 2023-10-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_count_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
    ]
