name: Quality
on: [ pull_request, workflow_call ]

jobs:
  quality:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10-alpine

    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: database
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry