name: Tests
on: [ push ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker
        run: docker compose up --build -d

      #      - name: Shell
      #        run: |
      #          docker exec recipe-web-app-1 sh
      - name: Check Containers
        run: docker ps
        
      - name: Check psql
        run: |
          docker exec recipe-database-1 psql -U postgres
          CREATE DATABASE postgres;
          exit

      - name: Start test
        run: |
          docker exec recipe-web-app-1 sh -c "python manage.py makemigrations"
          docker exec recipe-web-app-1 sh -c "python manage.py migrate --noinput"
          docker exec recipe-web-app-1 python manage.py test