name: Tests
on: [ pull_request ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    container: python:3.10-alpine
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd ./wok
          python3 manage.py test