name: Tests
on: [ push ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker
        run: docker compose up --build -d

      #      - name: Create db
      #        run: |
      #          docker exec recipe-web-app-1 sh
      #          sudo su - postgres
      #          psql -c "create database demo"

      - name: Start test
        run: docker exec recipe-web-app-1 python manage.py test