name: Tests
on: [ push ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        #          POSTGRES_DB: postgres
        #          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Start Postgresql
        run: sudo systemctl start postgresql.service

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        env:
          #          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: postgres
          POSTGRES_PASSWORD: postgres
        #          POSTGRES_PORT: 5432
        run: |
          cd ./wok
          python3 manage.py makemigrations
          python manage.py migrate
          python3 manage.py test