name: Tests
on: [ pull_request ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    container: python:3.10-alpine

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd ./wok
          python3 manage.py makemigrations
          python manage.py migrate
          python3 manage.py test
        env:
          PG_HOST: postgres
          PG_USER: postgres
          PG_DATABASE: postgres
          PG_PASSWORD: postgres
          PG_PORT: ${{ job.services.postgres.ports['5432'] }}