name: Tests
on: [ push ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker
        run: docker compose build

      - name: Start test
        run: docker compose test